config/routes.rb
Hb::Application.routes.draw do

  get '/login' => 'auth#login'
  get '/logout' => 'auth#logout'

  root to: 'welcome#index'

  get '/charts' => 'charts#index'
  match '/auth/do_it(&:format)' => 'auth#do_it'

  get '/mybets' => 'bets#index'

  get '/fake_session' => 'auth#fake_session'

  resources :user_bets

  get '/mybets/new' => 'bets#new'
  post '/bets/search' => 'bets#search'

  get '/admin' => 'admin#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :lastfm_url, :mbid, :name, :image

  has_many :bets

  def self.create_or_update!(artist)
    unless (@result = Artist.find_by_mbid(artist.mbid))
      @result = Artist.create!(
          mbid: artist.mbid,
          name: artist.name,
          lastfm_url: artist.lastfm_url,
          image: artist.image
      )
    end
    @result
  end
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist

  attr_accessible :artist, :user, :artist_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bets

  attr_accessible :name,
                  :vk_id,
                  :id,
                  :is_admin

  def do_bet(artist)
    return if bets.count == 10

    @artist = Artist.create_or_update!(artist)
    Bet.create!(:user_id => id, :artist => @artist) unless
        Bet.where("user_id = #{id} and artist_id = #{@artist.id}").first
  end
end

app/controllers/admin_controller.rb
#encoding: utf-8

class AdminController < ApplicationController

  skip_before_filter :check_access_rights
  before_filter :check_is_admin

  def index
    #
  end

  private

  def check_is_admin
    unless current_user? && current_user.is_admin?
      redirect_to '/mybets', notice: 'Вы не авторизованы'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :check_access_rights

  def current_user?
    not current_user.nil?
  end

  def current_user
    User.find(session[:current_user]) if session[:current_user]
  end

  def current_user=(user)
    session[:current_user] = user.id
  end

  helper_method :current_user
  helper_method :current_user=

  private

  def check_access_rights
    redirect_to :controller => :auth, :action => :login unless current_user?
  end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  skip_before_filter :check_access_rights
  before_filter :check_if_already_authenticated, :except => :logout

  def start_session
    #
  end

  def login
    #
  end

  def logout
    session[:current_user] = nil
    redirect_to '/'
  end

  def fake_session
    session[:current_user] = User.create!(:vk_id => 123456, :name => 'il.ya')
    redirect_to '/'
  end

  def do_it
    parse_token params[:format]

    redirect_to '/'
  end

  def parse_token(token)
    res = []
    token.split('&').each { |el| res << el.split('=') }

    @auth_params = Hash[*res.flatten!].symbolize_keys!
  end

  private

  def check_if_already_authenticated
    if current_user?
      redirect_to :controller => :bets
    end
  end

end

app/controllers/bets_controller.rb
#encoding: utf-8

require 'net/http'
require 'json'

class BetsController < ApplicationController

  def index
    #
  end

  def new
    [@search_results = params[:search_results] || [], @search_string = params[:search_string] || '']
  end

  def search
    @search_string = params[:search_string]

    search_api_url = URI.parse "http://ws.audioscrobbler.com/2.0/?method=artist.search&artist=#{URI.escape @search_string}&api_key=0e7add553b2e3a4e62e655323d407676&format=json"
    req = Net::HTTP::Get.new(search_api_url.to_s)
    res = Net::HTTP.start(search_api_url.host, search_api_url.port) do |http|
      http.request(req)
    end
    artists_json = JSON.parse(res.body)
    @search_results = []
    flash[:error] = nil

    if artists_json.has_key?('error')
      flash[:error] = 'По вашему запросу ничего не найдено :('
    elsif artists_json['results']['opensearch:totalResults'].to_i > 0
      artists_json['results']['artistmatches']['artist'].each do |artist|
        unless artist['mbid'].empty?
          @search_results << {
              mbid:         artist['mbid'],
              name:         artist['name'],
              lastfm_url:   artist['url'],
              image:        artist['image'].select{ |el| el['size'] == 'extralarge' }.first['#text']
          }
        end
      end
      flash[:error] = if @search_results.size == 0
                        'По вашему запросу ничего не найдено :('
                      elsif @search_results.size == 30
                        'Найдено более 30 исполнителей.'
                      end
      flash[:error] << 'Максимальное число ставок - 10 - превышенно.' if current_user.bets.count == 10
    else
      flash[:error] = 'По вашему запросу ничего не найдено :('
    end

    render :new
  end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  skip_before_filter :check_access_rights, :except => :index

  def index
    @artists = Artist.all.uniq.sort{ |a, b| b.bets.count <=> a.bets.count }
  end

end

app/controllers/user_bets_controller.rb
class UserBetsController < ApplicationController

  def new
    @artist = Artist.new(params[:artist])

    current_user.do_bet(@artist)

    redirect_to controller: :bets
  end

  def destroy
    Bet.find(params[:id]).destroy

    redirect_to :controller => :bets, :action => :index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user?
      redirect_to :controller => :bets
    else
      redirect_to :controller => :auth, :action => :login
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/user_bets_helper.rb
module UserBetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
Add head

app/views/bets/_search_results.html.erb
<div id="container">

  <% @search_results.each do |artist| %>
      <div class='box photo col2' style="text-align:center;">
        <img src="<%= artist[:image] %>" alt=""/>
        <h3>
          <br><%= artist[:name] %>
        </h3>

        <div class="box_comment"><p>Ставок: <b>1209</b></p></div>

        <div class="box_comment">
          <p>
            <% if controller.current_user.bets.count < 10 %>
                <%= link_to 'Сделать ставку', new_user_bet_path(:artist => artist), :class => 'alert button round' %>
            <% end %>
          </p>
        </div>

        <div class="box_comment">
          <p>
            <a href="<%= artist[:lastfm_url] %>" target="_blank" class="button round small">Профиль на Last.fm</a>
          </p>
        </div>
      </div>
  <% end %>

</div>

app/views/bets/index.html.erb
<div id="container">

  <% current_user.bets.each do |bet| %>
      <div class='box photo col2' style="text-align:center;">
        <img src='<%= bet.artist.image %>' />
        <h3>
          <strong><%= bet.artist.name %></strong>
        </h3>

        <div class="box_comment"><p>Ставок: <b>1209</b></p></div>

        <div class="box_comment">
          <p>
            <%= link_to 'Отменить ставку', user_bet_path(bet.id), :method => :delete, :class => 'alert button round remove_bet' %>
          </p>
        </div>

        <div class="box_comment">
          <p>
            <a href="<%= bet.artist.lastfm_url %>" target="_blank" class="button round small">Профиль на Last.fm</a>
          </p>
        </div>
      </div>
  <% end %>

</div>

app/views/bets/new.html.erb
<div class="row page_wrap" style="margin-top:-2px">
  <!-- page wrap -->
  <div class="twelve columns">
    <!-- page wrap -->

    <div class="row">

      <div class="heading_dots">
        <h3 class="heading_supersize">
          <span class="heading_center_bg">
            Поиск
          </span>
        </h3>
      </div>

      <p class="welcome_text">
        Введите название группы и нажимайте "Найти"
      </p>

      <div class="twelve columns">
        <%= form_tag(:action => :search) do %>
            <%= text_field_tag 'search_string', @search_string, :style => 'height:50px;font-family: Georgia, "Times New Roman", Times, serif;font-size:32px;' %>
            <p style="text-align:center">
              <%= button_tag 'Найти', :id => 'btnsrch', :class=> 'button alert large round' %>
            </p>
        <% end %>
      </div>

    </div>

  </div>

</div>

<%= render 'search_results', :locals => @search_results %>

app/views/charts/index.html.erb
<% @artists.each do |a| %>
    <div class="row page_wrap" style="margin-top:-2px">
      <div class="heading_dots_grey">
        <h2 style="text-align: center;" class="heading">
              <span class="heading_center_bg">
                <a href="<%= a.lastfm_url %>" target="_blank">
                  <%= "#{a.name} (#{Bet.where("artist_id=#{a.id}").count})" %>
                </a>
              </span>
        </h2>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8" />

  <meta name="viewport" content="width=device-width" />

  <title>Kubana heads bets</title>

  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
  <link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oranienbaum&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
  <!--<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>-->
  <!--<![endif]&ndash;&gt;-->

  <style type="text/css">
      .li_active
      {
          background: #000000; color: #fff; border: 0;
          font-weight: bold;
          /*width: 100%;*/
          -webkit-transition: all .2s ease-in-out;
          -moz-transition: all .2s ease-in-out;
          -ms-transition: all .2s ease-in-out;
          -o-transition: all .2s ease-in-out;
          transition: all .2s ease-in-out;
      }
  </style>


</head>
<body>

<div class="twelve columns header_nav_fullwidth">

  <a href="/mybets">
    <img src="/images/logo_black.png" alt="desc" style="border:none; margin:0 15px 7px; width: 90%;" />
  </a>

  <div class="ten columns">

    <% if current_user %>
        <ul id="menu-header" class="nav-bar horizontal">
          <li class="<%= 'li_active' if request.fullpath == '/mybets' %>">
            <%= link_to 'Мои ставки', :controller => :bets %>
          </li>
          <li class="<%= 'li_active' if request.fullpath == '/charts' %>">
            <%= link_to 'Чарты', :controller => :charts %>
          </li>
          <li class="">

          </li>
          <li class="<%= 'li_active' if request.fullpath == '/mybets/new' || request.fullpath ==  '/bets/search' %>">
            <%= link_to 'Сделать ставку!', '/mybets/new', :class => :newbet %>
          </li>
          <li class="">
            <%= link_to 'Выйти', :controller => :auth, :action => :logout %>
          </li>
        </ul>
    <% end %>


    <script type="text/javascript">
        //<![CDATA[
        $('ul#menu-header').nav-bar();
        //]]>
    </script>

  </div>

  <!-- <div class="two columns">
    <p style="margin: 6px 0">
      <a href="#" class="button radius">Sign up!</a> <a href="#" class="button secondary radius">Log in</a>
    </p>
  </div> -->

</div>

<!-- END Header -->

<div style="clear: both"></div>

<!-- page wrap -->
<div class="twelve columns">
  <!-- page wrap -->

  <!--alerts-->
  <div class="row page_wrap" style="margin-top:-2px">
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
            <h4 style="text-align: center;">
              <span class="heading_center_bg" style="font-family: Georgia, 'Times New Roman', Times, serif;">
                <%= msg %>
              </span>
            </h4>
        <% end %>
    <% end %>
  </div>

  <%= yield %>

  <div class="twelve columns">
    <ul id="menu3" class="footer_menu horizontal">
      <li class="">Created by <a href="http://sald.in">[il.ya saldin]</a></li>
    </ul>
  </div>
  <script type="text/javascript">
      //<![CDATA[
      $('ul#menu3').nav-bar();
      //]]>
  </script>

</div>
<!-- end page wrap) -->

<script type="text/javascript">
    //<![CDATA[
    $(function(){
        var $container = $('#container');
        $container.imagesLoaded( function(){
            $container.masonry({
                itemSelector : '.box',
                isFitWidth: true,
                isAnimated: true
            });
        });
    });
    //]]>
</script>
<!-- END Masonry -->

<!-- Included JS Files (Compressed) -->
<!--<script src="javascripts/foundation.min.js" type="text/javascript"></script>-->
<!-- Initialize JS Plugins -->
<!--<script src="javascripts/app.js" type="text/javascript"></script>-->
<!-- Masonry for galleries -->
<!--<script src="javascripts/masonry.js" type="text/javascript"></script>-->
<script type="text/javascript">
    //<![CDATA[
    $(function(){
        var $container = $('#container');
        $container.imagesLoaded( function(){
            $container.masonry({
                itemSelector : '.box',
                isFitWidth: true,
                isAnimated: true
            });
        });
    });
    //]]>
</script>

</body>
</html>